"""coop: extended models ledger loan schedule wallet hcs policy trust history

Revision ID: 1d97d62aca4f
Revises: c2cd60702d39
Create Date: 2025-08-29 17:40:56.746398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d97d62aca4f'
down_revision = 'c2cd60702d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.String(length=64), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_event_logs_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_event_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_event_logs_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_event_logs_tx_hash'), ['tx_hash'], unique=False)

    op.create_table('group_account_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('hedera_account_id', sa.String(length=64), nullable=False),
    sa.Column('hcs_topic_id', sa.String(length=64), nullable=True),
    sa.Column('treasury_token_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_account_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_account_links_group_id'), ['group_id'], unique=True)

    op.create_table('hcs_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('sequence_no', sa.BigInteger(), nullable=True),
    sa.Column('msg_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hcs_message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hcs_message_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hcs_message_logs_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hcs_message_logs_sequence_no'), ['sequence_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_hcs_message_logs_topic_id'), ['topic_id'], unique=False)

    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('quorum_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_loan_pct_of_pool', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_loan_per_member', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('min_deposit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('penalty_rate_monthly', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_group_id'), ['group_id'], unique=True)

    op.create_table('transaction_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('hcs_topic_id', sa.String(length=64), nullable=True),
    sa.Column('hcs_seq', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_ledger_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('trust_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('score_after', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('ref_table', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_score_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_score_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_score_history_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_score_history_user_id'), ['user_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_request_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate_apy', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_loan_request_id'), ['loan_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    op.create_table('voting_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('loan_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_request_id')
    )
    with op.batch_alter_table('voting_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voting_sessions_group_id'), ['group_id'], unique=False)

    op.create_table('repayment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_component', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_no', name='uq_loan_installment')
    )
    with op.batch_alter_table('repayment_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repayment_schedules_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_repayment_schedules_loan_id'), ['loan_id'], unique=False)

    op.create_table('vote_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['voting_sessions.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'voter_id', name='uq_session_voter')
    )
    with op.batch_alter_table('vote_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_details_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_details_voter_id'), ['voter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_details_voter_id'))
        batch_op.drop_index(batch_op.f('ix_vote_details_session_id'))

    op.drop_table('vote_details')
    with op.batch_alter_table('repayment_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repayment_schedules_loan_id'))
        batch_op.drop_index(batch_op.f('ix_repayment_schedules_due_date'))

    op.drop_table('repayment_schedules')
    with op.batch_alter_table('voting_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voting_sessions_group_id'))

    op.drop_table('voting_sessions')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))
        batch_op.drop_index(batch_op.f('ix_loans_loan_request_id'))
        batch_op.drop_index(batch_op.f('ix_loans_group_id'))
        batch_op.drop_index(batch_op.f('ix_loans_created_at'))

    op.drop_table('loans')
    with op.batch_alter_table('trust_score_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_score_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_trust_score_history_group_id'))
        batch_op.drop_index(batch_op.f('ix_trust_score_history_created_at'))

    op.drop_table('trust_score_history')
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_ledger_group_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_ledger_created_at'))

    op.drop_table('transaction_ledger')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_group_id'))

    op.drop_table('policy_rules')
    with op.batch_alter_table('hcs_message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hcs_message_logs_topic_id'))
        batch_op.drop_index(batch_op.f('ix_hcs_message_logs_sequence_no'))
        batch_op.drop_index(batch_op.f('ix_hcs_message_logs_group_id'))
        batch_op.drop_index(batch_op.f('ix_hcs_message_logs_created_at'))

    op.drop_table('hcs_message_logs')
    with op.batch_alter_table('group_account_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_account_links_group_id'))

    op.drop_table('group_account_links')
    with op.batch_alter_table('contract_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_event_logs_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_contract_event_logs_group_id'))
        batch_op.drop_index(batch_op.f('ix_contract_event_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_contract_event_logs_contract_id'))

    op.drop_table('contract_event_logs')
    # ### end Alembic commands ###
