"""Add interest_rate and min_balance to CooperativeGroup

Revision ID: 4c86cc64cac6
Revises: 95f714a4f72a
Create Date: 2025-09-02 16:59:17.304017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c86cc64cac6'
down_revision = '95f714a4f72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative_groups', schema=None) as batch_op:
        batch_op.drop_column('min_balance')
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###
