"""Add hedera_private_key to CooperativeGroup

Revision ID: 5f69a13dbdba
Revises: cbf1b2b6d3c6
Create Date: 2025-08-31 18:36:09.594532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f69a13dbdba'
down_revision = 'cbf1b2b6d3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hedera_private_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative_groups', schema=None) as batch_op:
        batch_op.drop_column('hedera_private_key')

    # ### end Alembic commands ###
