"""update transaction_history with new cols

Revision ID: 93b3dc186a32
Revises: ac4e5e0e4fa4
Create Date: 2025-08-22 13:13:49.968054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b3dc186a32'
down_revision = 'ac4e5e0e4fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('token_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('from_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.drop_column('meta')
        batch_op.drop_column('to_account')
        batch_op.drop_column('from_account')
        batch_op.drop_column('token_id')
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###
