"""Add MemberBalance model

Revision ID: 95f714a4f72a
Revises: 5f69a13dbdba
Create Date: 2025-09-01 20:15:11.595508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f714a4f72a'
down_revision = '5f69a13dbdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_earned', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user_balance')
    )
    with op.batch_alter_table('member_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_balances_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_balances_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_balances_user_id'))
        batch_op.drop_index(batch_op.f('ix_member_balances_group_id'))

    op.drop_table('member_balances')
    # ### end Alembic commands ###
