"""add payment_orders and payment_attempts tables

Revision ID: a08de9fc5264
Revises: e6346fbcf6e4
Create Date: 2025-09-24 09:44:17.139097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08de9fc5264'
down_revision = 'e6346fbcf6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted! ###
    op.create_table(
        'payment_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=True),
        sa.Column('msisdn', sa.String(length=32), nullable=False),
        sa.Column('mpesa_ref', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('hedera_tx_hash', sa.String(length=128), nullable=True),
        sa.Column('mpesa_raw_payload', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_id'),
        sa.UniqueConstraint('mpesa_ref')
    )

    op.create_table(
        'payment_attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.String(length=64), nullable=False),
        sa.Column('msisdn', sa.String(length=32), nullable=False),
        sa.Column('mpesa_ref', sa.String(length=64), nullable=True),
        sa.Column('amount', sa.Numeric(12, 2), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('hedera_tx_hash', sa.String(length=128), nullable=True),
        sa.Column('mpesa_response', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['payment_orders.order_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted! ###
    op.drop_table('payment_attempts')
    op.drop_table('payment_orders')
    # ### end Alembic commands ###

