"""Fix KYCRequest model with document fields

Revision ID: ac4e5e0e4fa4
Revises: bfaa7a5acdde
Create Date: 2025-08-21 13:15:53.656814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4e5e0e4fa4'
down_revision = 'bfaa7a5acdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('submitted_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_requests', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###
