"""Add Hedera + salary tracking (fixed)

Revision ID: bfaa7a5acdde
Revises: e07965a8b373
Create Date: 2025-08-19 17:32:53.364914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaa7a5acdde'
down_revision = 'e07965a8b373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hedera_tx_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hedera_path', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_history_recipient', 'users', ['recipient_id'],  ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hedera_path')
        batch_op.drop_column('hedera_tx_id')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
