"""add purpose field to LoanRequest

Revision ID: cbf1b2b6d3c6
Revises: 1d97d62aca4f
Create Date: 2025-08-29 18:01:55.709381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf1b2b6d3c6'
down_revision = '1d97d62aca4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_requests', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
