"""add hedera_private_key

Revision ID: e352aea4c351
Revises: 93b3dc186a32
Create Date: 2025-08-26 00:06:24.511647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e352aea4c351'
down_revision = '93b3dc186a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hedera_private_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hedera_private_key')

    # ### end Alembic commands ###
